KS 4 4 sport training
Macstar1/KotlinSprint pull request #19
Opened 2024-05-04 13:59 UTC by Macstar1

2024-05-05 13:22 UTC, ievetrovdev requested changes

2024-05-05 13:22 UTC, ievetrovdev commented on src/main/kotlin/Lesson4/lesson_4_task_4.kt
> +    var parity = dayOfTraining % 2
Можно сразу здесь проверить на четность, затем применить к каждой части тела напрямую или с отрицанием (инвертируя значение через символ !)

2024-05-05 13:32 UTC, Macstar1 commented
Изменил в соответствии с рекомендациями.

2024-05-06 06:55 UTC, ievetrovdev approved these changes

2024-05-06 06:56 UTC, merged