KS-4-5 ship voyage
Macstar1/KotlinSprint pull request #20
Opened 2024-05-04 19:45 UTC by Macstar1

2024-05-05 13:24 UTC, ievetrovdev requested changes
> Использование оператора !! подразумевает, что ты уверен в том, что значение не может быть null. Однако, если это не так, то приложение "упадет" с ошибкой.
Это противоречит основной идее безопасности типов в Kotlin, поэтому лучше использовать альтернативные способы обработки нулабельных значений. такие как оператор безопасного вызова ?., элвис-оператор ?: или оператор let

В данном случае лучше использовать функцию readln() для чтения с консоли, которая не будет выбрасывать исключение, если в нее придет null, а просто вернет строку (строка будет конфликтовать с приведением к целочисленному типу, но это другой кейс, важнее разобраться с нулябельностью). Она появилась относительно недавно, поэтому ее нет в видео гайдах.
>

2024-05-05 13:24 UTC, ievetrovdev commented on src/main/kotlin/Lesson4/lesson_4_task_5.kt
> +    val shipDamage = readLine().toBoolean()
Неочевидный нейминг переменных. также напоминаю, что boolean переменные именуются в основном начиная с is

2024-05-05 13:24 UTC, ievetrovdev commented on src/main/kotlin/Lesson4/lesson_4_task_5.kt
> +        (!shipDamage && (MIN_CRUE_VALUE <= shipCrew!!) && (shipCrew <= MAX_CRUE_VALUE) && (food!! > FOOD) && weather) || (shipDamage && (shipCrew == MAX_CRUE_VALUE) && weather && (food!! >= FOOD))
Для длинных условий, которые не помещаются в одну строку, лучше сделать перенос строки после оператора || или &&
Официальная документация [Kotlin Coding Conventions](https://kotlinlang.org/docs/coding-conventions.html) не дает строгих указаний на тему переноса строк внутри условий. Но такой формат я встречал чаще

2024-05-05 13:56 UTC, Macstar1 commented
Исправил в соответствии с замечаниями.

2024-05-06 06:56 UTC, ievetrovdev approved these changes

2024-05-06 14:49 UTC, merged