KS-5-5 lottery
Macstar1/KotlinSprint pull request #25
Opened 2024-05-06 03:31 UTC by Macstar1

2024-05-06 06:50 UTC, Macstar1 commented
По идее нужно сделать проверку на совпадение случайных значений, если они есть, запустить генерацию снова, именно поэтому использовал mutableListOf. Если честно, без цикла не придумал как её реализовать, а мы их ещё не проходили :)
Также есть сомнения в генерации случайных значений для каждого элемента.

2024-05-06 18:56 UTC, ievetrovdev requested changes
Это 5 задача ("со звездочкой") не по уровню урока, и решение может потребовать дополнительного ресерча). Поэтому в целом все отлично! небольшие замечания)

2024-05-06 18:56 UTC, ievetrovdev commented on src/main/kotlin/Lesson5/lesson_5_task_5.kt
> +fun main() {
Изначально нужно вывести сообщение пользователю о вводе чисел)

2024-05-06 18:56 UTC, ievetrovdev commented on src/main/kotlin/Lesson5/lesson_5_task_5.kt
> +import kotlin.random.Random
Любой импорт – лишний код в классе. Существуют условно тонкие материи, когда надо использовать какую-то конкретную реализацию под капотом. Поэтому обоснованно может быть вызвать некую альтернативу из Котлин или похожий функционал, но с другим внутренним алгоритмом из Джавы. Ситуативно. Здесь я бы использовал экстеншн получения рандомного числа из диапазона: (1..10).random()

2024-05-06 18:56 UTC, ievetrovdev commented on src/main/kotlin/Lesson5/lesson_5_task_5.kt
> +    val randomValues = listOf(Random.nextInt(0, 42), Random.nextInt(0, 42), Random.nextInt(0, 42))
Очень длинная строка получилась (более 120 символов). В крупных и средних проектах есть системы для автоматизированной проверки кода, например: [Detekt](https://detekt.dev/docs/rules/formatting/#maximumlinelength), который не пропустит такой код. Давай добавим переносов

2024-05-06 21:25 UTC, Macstar1 commented
Исправил получение рандомного числа на экстеншн метод, благодаря чему уменьшилась длина строк. Также добавил проверку на совпадающие элементы.

2024-05-07 15:47 UTC, ievetrovdev approved these changes

2024-05-07 15:48 UTC, merged