KS-1-5 translate seconds to minutes and hours
Macstar1/KotlinSprint pull request #5
Opened 2024-05-01 14:53 UTC by Macstar1

Добавление нуля для секунд подсмотрел в интернете.

2024-05-02 10:37 UTC, ievetrovdev requested changes

2024-05-02 10:37 UTC, ievetrovdev commented on src/main/kotlin/Lesson1/lesson_1_task_5.kt
> +    var minutes  = seconds / 60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-05-02 10:37 UTC, ievetrovdev commented on src/main/kotlin/Lesson1/lesson_1_task_5.kt
> +    println("$hours:$finalMinutes:$finalSeconds")
Верный подход, но можно аккуратнее сделать, без дополнительных переменных
println("%02d:%02d:%02d".format(hours, minutes, seconds))
в этом случае не потеряется ноль в выводе часов)

2024-05-02 11:54 UTC, Macstar1 commented
Исправил в соответствии с рекомендациями.

2024-05-02 13:51 UTC, Macstar1 commented
Закоммитил сюда файл из другого урока. Пытаюсь разобраться как его отсюда удалить. В следующий урок, вроде, получилось его закоммитить.

2024-05-03 07:02 UTC, ievetrovdev approved these changes

2024-05-03 07:04 UTC, ievetrovdev requested changes
Убери, плиз лишний файл попал

2024-05-03 07:06 UTC, ievetrovdev commented
> Закоммитил сюда файл из другого урока. Пытаюсь разобраться как его отсюда удалить. В следующий урок, вроде, получилось его закоммитить.

Тут нужно в данном пулл реквесте надо:
- переключиться в ветку текущего ПР
- удалить лишний файл с задачей (физически из проекта)
- сделать коммит (с изменением удаления)
- прислать ссылку на этот же пулл реквест снова в бот

2024-05-03 07:16 UTC, Macstar1 commented
Вроде получилось. Сейчас пройдусь по остальным урокам

2024-05-03 18:33 UTC, ievetrovdev approved these changes

2024-05-03 18:33 UTC, ievetrovdev commented on src/main/kotlin/Lesson1/lesson_1_task_5.kt
> +fun main(){
Не забывай прожимать автоформатирование перед коммитом не хватает пробела Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx)

В остальном все отлично!

2024-05-03 18:35 UTC, merged